/* Item-level packing compositions plus optional general shipment summary. */
S.useGeneralPack ??= false;
S.generalPack ??= {cartons:'',packages:'',qty:'',length:'',width:'',height:'',net:'',gross:'',marks:'CENTRAL MESH / '+client().name,notes:''};

document.head.insertAdjacentHTML('beforeend',`<style>
.packmode{background:#17191a;color:#fff;padding:18px;margin-bottom:18px;display:grid;grid-template-columns:1fr 290px;gap:20px;align-items:center}.packmode h3{margin:0 0 5px}.packmode p{margin:0;color:#bec4c5}.packmode select{font-size:15px;font-weight:800}.itemgroup{border:1px solid var(--stroke);background:#f2f0e9;margin:18px 0;padding:14px}.itemgrouphead{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:12px}.itemgrouphead h3{margin:0;font-size:16px}.itemgrouphead small{display:block;color:var(--muted);margin-top:4px}.generalpack{border:2px solid #202324;background:#fffbea}.generalpack .logrowhead{background:#ffe500;margin:-16px -16px 14px;padding:12px 16px}.scopebadge{background:#242829;color:#fff;padding:5px 8px;font-size:10px;letter-spacing:.08em}.totalsCompare{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.totalsBox{background:#fff;border:1px solid var(--stroke);padding:16px}.totalsBox.active{border-top:4px solid var(--yellow)}.totalsBox h4{margin:0 0 10px}.totalsLine{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #eee}@media(max-width:800px){.packmode,.totalsCompare{grid-template-columns:1fr}}
</style>`);

function packingItems(){
  const out=[];
  S.orders.forEach((order,oi)=>order.items.forEach((item,ii)=>out.push({ref:`${order.order||oi}::${item.code||ii}::${ii}`,order:order.order||'',po:order.customerPO||'',item,oi,ii,label:`${item.code||'Item '+(ii+1)} — ${item.description||item.source||'Sem descrição'}`})));
  return out;
}
function emptyItemPack(ref){const entry=packingItems().find(x=>x.ref===ref);return {itemRef:ref,box:S.packs.length+1,cartons:1,piecesPerCarton:'',packages:1,packagesPerCarton:'',netPerPackage:'',cartonTare:'',netPerCarton:'',grossPerCarton:'',description:entry?.item.description||'',length:'',width:'',height:'',net:'',gross:'',marks:'CENTRAL MESH / '+client().name,notes:''}}
function ensureItemPacks(){
  const items=packingItems(),refs=new Set(items.map(x=>x.ref));
  S.packs=S.packs.filter(x=>!x.itemRef||refs.has(x.itemRef));
  const legacy=S.packs.filter(x=>!x.itemRef);legacy.forEach((x,i)=>x.itemRef=items[Math.min(i,Math.max(0,items.length-1))]?.ref||'');
  items.forEach(entry=>{if(!S.packs.some(x=>x.itemRef===entry.ref))S.packs.push(emptyItemPack(entry.ref))});
  S.packs.forEach((x,i)=>{x.box=i+1;if(!x.description)x.description=items.find(v=>v.ref===x.itemRef)?.item.description||''});
  quietSave();
}
function addItemPack(ref){S.packs.push(emptyItemPack(ref));quietSave();renderLogistics()}
function removeItemPack(index){const ref=S.packs[index]?.itemRef;if(S.packs.filter(x=>x.itemRef===ref).length===1)return alert('Cada item precisa manter pelo menos uma composição individual.');if(!confirm('Excluir esta composição individual?'))return;S.packs.splice(index,1);quietSave();renderLogistics()}
function setGeneralMode(value){S.useGeneralPack=value==='yes';quietSave();renderLogistics()}
function setGeneralPack(key,value){S.generalPack[key]=['marks','notes'].includes(key)?value:Number(value);quietSave();renderLogTotals()}
function individualTotals(){return S.packs.reduce((a,x)=>({cartons:a.cartons+(+x.cartons||0),packages:a.packages+(+x.packages||0),qty:a.qty+(+x.qty||0),net:a.net+(+x.net||0),gross:a.gross+(+x.gross||0)}),{cartons:0,packages:0,qty:0,net:0,gross:0})}
function packingTotals(){const p=S.useGeneralPack?S.generalPack:individualTotals();return {cartons:+p.cartons||0,packages:+p.packages||0,qty:+p.qty||0,net:+p.net||0,gross:+p.gross||0}}

function generalFields(){const x=S.generalPack;return `<div class="logrow generalpack"><div class="logrowhead"><div><span class="scopebadge">RESUMO GERAL</span><strong style="margin-left:9px">Carga completa</strong></div><span>Opcional</span></div><div class="logistics-grid"><label>Total de caixas<input type="number" value="${esc(x.cartons)}" oninput="setGeneralPack('cartons',this.value)"></label><label>Total de pacotes<input type="number" value="${esc(x.packages)}" oninput="setGeneralPack('packages',this.value)"></label><label>Total de peças<input type="number" value="${esc(x.qty)}" oninput="setGeneralPack('qty',this.value)"></label><label>Peso líquido geral kg<input type="number" step=".001" value="${esc(x.net)}" oninput="setGeneralPack('net',this.value)"></label><label>Peso bruto geral kg<input type="number" step=".001" value="${esc(x.gross)}" oninput="setGeneralPack('gross',this.value)"></label><label>Comprimento geral cm<input type="number" step=".01" value="${esc(x.length)}" oninput="setGeneralPack('length',this.value)"></label><label>Largura geral cm<input type="number" step=".01" value="${esc(x.width)}" oninput="setGeneralPack('width',this.value)"></label><label>Altura geral cm<input type="number" step=".01" value="${esc(x.height)}" oninput="setGeneralPack('height',this.value)"></label><label class="full">Marcas gerais<input value="${esc(x.marks)}" oninput="setGeneralPack('marks',this.value)"></label><label class="full">Observações gerais<textarea oninput="setGeneralPack('notes',this.value)">${esc(x.notes)}</textarea></label></div></div>`}
function itemPackCard(x,index,composition){return `<div class="logrow"><div class="logrowhead"><div><span class="scopebadge">ITEM</span><strong style="margin-left:9px">Composição ${composition}</strong></div><button class="btn light mini danger" onclick="removeItemPack(${index})">Excluir</button></div><div class="logistics-grid"><div class="sectionlabel">COMPOSIÇÃO INDIVIDUAL DO ITEM</div><label>Quantidade de caixas<input type="number" value="${esc(x.cartons)}" onchange="setPack(${index},'cartons',this.value)"></label><label>Peças por caixa<input type="number" value="${esc(x.piecesPerCarton)}" onchange="setPack(${index},'piecesPerCarton',this.value)"></label><label>Pacotes por caixa<input type="number" value="${esc(x.packagesPerCarton)}" onchange="setPack(${index},'packagesPerCarton',this.value)"></label><label>Peso líquido por pacote kg<input type="number" step=".001" value="${esc(x.netPerPackage)}" onchange="setPack(${index},'netPerPackage',this.value)"></label><label>Tara da caixa kg<input type="number" step=".001" value="${esc(x.cartonTare)}" onchange="setPack(${index},'cartonTare',this.value)"></label><label>Peso líquido por caixa kg<input type="number" step=".001" value="${esc(x.netPerCarton)}" onchange="setPack(${index},'netPerCarton',this.value)"></label><label>Peso bruto por caixa kg<input type="number" step=".001" value="${esc(x.grossPerCarton)}" onchange="setPack(${index},'grossPerCarton',this.value)"></label><label>Total de pacotes<input type="number" value="${esc(x.packages)}" onchange="setPack(${index},'packages',this.value)"></label><div class="sectionlabel">TOTAIS DESTA COMPOSIÇÃO</div><label>Quantidade total de peças<input type="number" value="${esc(x.qty)}" onchange="setPack(${index},'qty',this.value)"></label><label>Peso líquido total kg<input type="number" step=".001" value="${esc(x.net)}" onchange="setPack(${index},'net',this.value)"></label><label>Peso bruto total kg<input type="number" step=".001" value="${esc(x.gross)}" onchange="setPack(${index},'gross',this.value)"></label><label>Comprimento cm<input type="number" step=".01" value="${esc(x.length)}" onchange="setPack(${index},'length',this.value)"></label><label>Largura cm<input type="number" step=".01" value="${esc(x.width)}" onchange="setPack(${index},'width',this.value)"></label><label>Altura cm<input type="number" step=".01" value="${esc(x.height)}" onchange="setPack(${index},'height',this.value)"></label><div class="calcHint">Os totais são calculados automaticamente, mas permanecem editáveis.</div><label class="full">Descrição do item<textarea onchange="setPack(${index},'description',this.value)">${esc(x.description)}</textarea></label><label class="full">Marcas / identificação<input value="${esc(x.marks)}" onchange="setPack(${index},'marks',this.value)"></label><label class="full">Observações da Expedição<textarea onchange="setPack(${index},'notes',this.value)">${esc(x.notes)}</textarea></label></div></div>`}

renderLogistics=function(){
  ensureItemPacks();
  const oldAdd=stage3.querySelector('.panelhead .backcta');if(oldAdd)oldAdd.style.display='none';
  const items=packingItems();
  const groups=items.map(entry=>{const rows=S.packs.map((x,i)=>({x,i})).filter(v=>v.x.itemRef===entry.ref);return `<section class="itemgroup"><div class="itemgrouphead"><div><h3>${esc(entry.label)}</h3><small>Pedido ${esc(entry.order)} · PO ${esc(entry.po)} · Quantidade da Invoice: ${esc(entry.item.qty)}</small></div><button class="backcta" onclick="addItemPack('${esc(entry.ref)}')">+ Outra composição deste item</button></div>${rows.map((v,n)=>itemPackCard(v.x,v.i,n+1)).join('')}</section>`}).join('');
  logisticsRows.innerHTML=`<div class="packmode"><div><h3>Existe peso/embalagem geral da carga?</h3><p>Se não existir, selecione “Não há”. A Packing List usará a soma das composições individuais.</p></div><label>Resumo geral<select onchange="setGeneralMode(this.value)"><option value="no" ${!S.useGeneralPack?'selected':''}>Não há — usar itens individuais</option><option value="yes" ${S.useGeneralPack?'selected':''}>Sim — informar resumo geral</option></select></label></div>${S.useGeneralPack?generalFields():''}${groups}<div id="logTotals"></div>`;
  renderLogTotals();
}
renderLogTotals=function(){
  if(!document.getElementById('logTotals'))return;const ind=individualTotals(),official=packingTotals();
  logTotals.innerHTML=`<div class="totalsCompare"><div class="totalsBox"><h4>Soma dos itens individuais</h4><div class="totalsLine"><span>Caixas</span><b>${ind.cartons}</b></div><div class="totalsLine"><span>Pacotes</span><b>${ind.packages}</b></div><div class="totalsLine"><span>Peças</span><b>${ind.qty}</b></div><div class="totalsLine"><span>Peso líquido</span><b>${ind.net.toFixed(3)} kg</b></div><div class="totalsLine"><span>Peso bruto</span><b>${ind.gross.toFixed(3)} kg</b></div></div><div class="totalsBox active"><h4>Total oficial da Packing List</h4><div class="muted">${S.useGeneralPack?'Resumo geral informado pela Expedição':'Não há geral: soma automática dos itens'}</div><div class="totalsLine"><span>Caixas</span><b>${official.cartons}</b></div><div class="totalsLine"><span>Pacotes</span><b>${official.packages}</b></div><div class="totalsLine"><span>Peças</span><b>${official.qty}</b></div><div class="totalsLine"><span>Peso líquido</span><b>${official.net.toFixed(3)} kg</b></div><div class="totalsLine"><span>Peso bruto</span><b>${official.gross.toFixed(3)} kg</b></div></div></div>`;
}
processDocuments=function(){
  logisticsError.textContent='';ensureItemPacks();
  for(const entry of packingItems()){
    const rows=S.packs.filter(x=>x.itemRef===entry.ref);
    if(!rows.length||rows.some(x=>!(+x.cartons)||!(+x.packages)||!(+x.net)||!(+x.gross)))return logisticsError.textContent='Complete caixas, pacotes e pesos de cada composição do item '+entry.item.code+'.';
    if(rows.some(x=>+x.gross<+x.net))return logisticsError.textContent='O peso bruto não pode ser menor que o líquido no item '+entry.item.code+'.';
    const packed=rows.reduce((a,x)=>a+(+x.qty||0),0);if(+entry.item.qty&&packed!==+entry.item.qty)return logisticsError.textContent=`A quantidade embalada do item ${entry.item.code} é ${packed}, mas a Invoice possui ${entry.item.qty}.`;
  }
  if(S.useGeneralPack&&(!(+S.generalPack.cartons)||!(+S.generalPack.packages)||!(+S.generalPack.net)||!(+S.generalPack.gross)))return logisticsError.textContent='Complete caixas, pacotes e pesos do resumo geral ou selecione “Não há”.';
  if(S.useGeneralPack&&+S.generalPack.gross<+S.generalPack.net)return logisticsError.textContent='No resumo geral, o peso bruto não pode ser menor que o líquido.';
  quietSave();saveInvoiceHistory();goStep(4);
}

const saveInvoiceHistoryV6=saveInvoiceHistory;
saveInvoiceHistory=function(){saveInvoiceHistoryV6();const records=history(),record=records.find(x=>x.invoiceNo===S.invoiceNo),t=packingTotals();if(record){Object.assign(record,{cartons:t.cartons,packages:t.packages,net:t.net,gross:t.gross,data:JSON.parse(JSON.stringify(S))});localStorage.setItem('cm-invoice-history',JSON.stringify(records))}}

const renderDocsV6=renderDocs;
renderDocs=function(){
  renderDocsV6();const items=packingItems(),t=packingTotals();
  const old=[...packingView.querySelectorAll('.docnote')].find(n=>n.querySelector('b')?.textContent==='PACKAGING DETAILS');old?.remove();
  const rows=S.packs.map(x=>{const e=items.find(v=>v.ref===x.itemRef);return `<tr><td>${esc(e?.item.code||'—')}</td><td>${esc(x.cartons)}</td><td>${esc(x.piecesPerCarton)}</td><td>${esc(x.packagesPerCarton)}</td><td>${esc(x.netPerPackage)}</td><td>${esc(x.netPerCarton)}</td><td>${esc(x.grossPerCarton)}</td><td>${esc(x.net)}</td><td>${esc(x.gross)}</td></tr>`}).join('');
  const detail=`<div class="docnote"><b>ITEM PACKAGING DETAILS</b><table><tr><th>Item</th><th>Cartons</th><th>Pc/Carton</th><th>Packs/Carton</th><th>Net/Pack</th><th>Net/Carton</th><th>Gross/Carton</th><th>Net Total</th><th>Gross Total</th></tr>${rows}</table></div>${S.useGeneralPack?`<div class="docnote"><b>GENERAL SHIPMENT SUMMARY</b>Cartons: ${t.cartons} · Packages: ${t.packages} · Pieces: ${t.qty} · Net: ${t.net.toFixed(3)} kg · Gross: ${t.gross.toFixed(3)} kg<br>${esc(S.generalPack.notes||'')}</div>`:`<div class="docnote"><b>GENERAL SHIPMENT SUMMARY</b>Not provided — official totals are the sum of the individual items.</div>`}`;
  packingView.querySelector('.total')?.insertAdjacentHTML('beforebegin',detail);const total=packingView.querySelector('.total');if(total)total.textContent=`PACKAGES ${t.packages} · CARTONS ${t.cartons} · NET ${t.net.toFixed(3)} KG · GROSS ${t.gross.toFixed(3)} KG`;
  const signature=`<div class="docnote" style="margin-top:28px"><b>AUTHORIZED SIGNATURE</b><div style="height:64px;border-bottom:1px solid #333"></div></div>`;
  invoiceView.querySelector('.paper')?.insertAdjacentHTML('beforeend',signature);packingView.querySelector('.paper')?.insertAdjacentHTML('beforeend',signature);
}


downloadPDF=async function(){
  if(!S.orders.length)return alert('Importe um pedido primeiro.');
  const{jsPDF}=window.jspdf,d=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),ld=await logo(),pageW=297,margin=10,contentW=277,po=S.poDisplay||S.orders.map(o=>o.customerPO||o.order).join(', '),t=packingTotals();
  const dark=[37,41,43],line=[205,205,200];
  const partyText=p=>`${p.name||''}\n${p.address||''}\nTax ID: ${p.tax||''}${p.phone?'\nTel: '+p.phone:''}`;
  const pageHeader=title=>{d.addImage(ld,'PNG',margin,6,57,21);d.setFont('helvetica','bold');d.setFontSize(17);d.setTextColor(...dark);d.text(title,pageW-margin,16,{align:'right'});d.setDrawColor(...dark);d.line(margin,31,pageW-margin,31);const half=contentW/2;for(const [x,label,party] of [[margin,'SHIPPER',S.exporter],[margin+half,'CONSIGNEE',client()]]){d.setFillColor(...dark);d.rect(x,34,half,7,'F');d.setTextColor(255);d.setFont('helvetica','bold');d.setFontSize(7.5);d.text(label,x+2,38.7);d.setDrawColor(...line);d.rect(x,41,half,15);d.setTextColor(70);d.setFont('helvetica','normal');d.setFontSize(6.8);d.text(d.splitTextToSize(partyText(party),half-4),x+2,44,{lineHeightFactor:1.15})}const rows=[[['Invoice / Packing No.',S.invoiceNo],['Invoice Date',S.invoiceDate]],[['Delivery Date',S.deliveryDate],['Incoterm',S.incoterm]],[['PO',po],['Currency','USD']],[['Payment Terms',S.payment],['Transport',S.transport]],[['Origin / Destination',S.origin+' / '+S.destination],['Notify Party',S.notifyParty||'Same as consignee']]];const labelW=42,valueW=half-labelW,rowY=59,rowH=6;rows.forEach((pairs,ri)=>pairs.forEach(([label,value],pi)=>{const x=margin+pi*half,y=rowY+ri*rowH;d.setDrawColor(...line);d.rect(x,y,labelW,rowH);d.rect(x+labelW,y,valueW,rowH);d.setTextColor(75);d.setFont('helvetica','bold');d.setFontSize(6.5);d.text(label,x+1.5,y+4);d.setFont('helvetica','normal');d.setFontSize(6.3);d.text(d.splitTextToSize(String(value||''),valueW-3)[0]||'',x+labelW+1.5,y+4)}));return rowY+rows.length*rowH+4};
  const signature=(startY)=>{let y=startY;if(y>176){d.addPage();y=18}d.setFillColor(...dark);d.rect(margin,y,contentW,7,'F');d.setTextColor(255);d.setFont('helvetica','bold');d.setFontSize(8);d.text('AUTHORIZED SIGNATURE',margin+2,y+4.8);d.setDrawColor(...dark);d.line(margin,y+32,pageW-margin,y+32)};
  const footer=()=>{const pages=d.getNumberOfPages();for(let p=1;p<=pages;p++){d.setPage(p);d.setFontSize(6.5);d.setTextColor(100);d.text(`Central Mesh - ${S.invoiceNo} - Page ${p} of ${pages}`,pageW-margin,204,{align:'right'})}};
  let y=pageHeader('COMMERCIAL INVOICE');
  d.autoTable({startY:y,margin:{left:margin,right:margin},tableWidth:contentW,head:[['Item','NCM/HS Code','Description','Net Weight (kg)','Qty.','Unit Value (USD)','Total Value (USD)']],body:allItems().map((x,i)=>[i+1,x.hs,x.description,x.netWeight||'',x.qty,usd(x.unitBRL/S.fx),usd(x.qty*x.unitBRL/S.fx)]),theme:'grid',styles:{fontSize:7,cellPadding:1.8,lineColor:line,valign:'top'},headStyles:{fillColor:dark,textColor:255},columnStyles:{0:{cellWidth:12},1:{cellWidth:27},2:{cellWidth:113},3:{cellWidth:27,halign:'right'},4:{cellWidth:25,halign:'right'},5:{cellWidth:34,halign:'right'},6:{cellWidth:39,halign:'right'}}});
  y=d.lastAutoTable.finalY+3;const goods=usdTotal(),final=goods+(+S.freightUSD||0)+(+S.insuranceUSD||0)+(+S.otherUSD||0);d.autoTable({startY:y,margin:{left:195,right:margin},tableWidth:92,body:[['Goods Value',usd(goods)],['Freight',usd(S.freightUSD)],['Insurance',usd(S.insuranceUSD)],['Other Charges',usd(S.otherUSD)],['TOTAL',usd(final)]],theme:'grid',styles:{fontSize:7.3,cellPadding:1.5,lineColor:line},columnStyles:{0:{fontStyle:'bold'},1:{halign:'right'}},didParseCell:data=>{if(data.row.index===4){data.cell.styles.fillColor=dark;data.cell.styles.textColor=255;data.cell.styles.fontStyle='bold'}}});
  y=d.lastAutoTable.finalY+3;d.autoTable({startY:y,margin:{left:margin,right:margin},tableWidth:contentW,body:[['Declaration / Notes',S.declaration||''],['Beneficiary / Bank / SWIFT / IBAN',[S.exporter.beneficiary,S.exporter.bank,S.exporter.bankAddress,'SWIFT '+S.exporter.swift,S.exporter.account,S.exporter.intermediaryBank].filter(Boolean).join(' - ')]],theme:'grid',styles:{fontSize:6.8,cellPadding:1.8,lineColor:line},columnStyles:{0:{cellWidth:46,fontStyle:'bold'},1:{cellWidth:231}}});signature(d.lastAutoTable.finalY+4);
  d.addPage('a4','landscape');y=pageHeader('PACKING LIST');
  const packRows=S.packs.map((x,i)=>[i+1,x.description||connectedDescription(),x.qty||(+x.cartons*+x.piecesPerCarton),x.cartons,x.piecesPerCarton,x.packagesPerCarton,x.netPerPackage,x.netPerCarton,x.grossPerCarton,x.length||0,x.width||0,x.height||0,x.net,x.gross]);
  packRows.push(['OFFICIAL TOTAL',S.useGeneralPack?'General shipment summary':'Sum of individual items',t.qty,t.cartons,'',t.packages,'','','','','','',t.net,t.gross]);
  d.autoTable({startY:y,margin:{left:margin,right:margin},tableWidth:contentW,head:[['Box','Description','Qty.','Cartons','Pieces / Carton','Packs / Carton','Net / Pack kg','Net / Carton kg','Gross / Carton kg','Length cm','Width cm','Height cm','Net Total kg','Gross Total kg']],body:packRows,theme:'grid',styles:{fontSize:5.2,cellPadding:1.2,lineColor:line,valign:'top'},headStyles:{fillColor:dark,textColor:255},columnStyles:{0:{cellWidth:13},1:{cellWidth:75},2:{cellWidth:19,halign:'right'},3:{cellWidth:16,halign:'right'},4:{cellWidth:20,halign:'right'},5:{cellWidth:19,halign:'right'},6:{cellWidth:18,halign:'right'},7:{cellWidth:18,halign:'right'},8:{cellWidth:19,halign:'right'},9:{cellWidth:14,halign:'right'},10:{cellWidth:14,halign:'right'},11:{cellWidth:14,halign:'right'},12:{cellWidth:14,halign:'right'},13:{cellWidth:14,halign:'right'}},didParseCell:data=>{if(data.section==='body'&&data.row.index===packRows.length-1){data.cell.styles.fontStyle='bold';data.cell.styles.fillColor=[242,240,233]}}});
  y=d.lastAutoTable.finalY+3;d.autoTable({startY:y,margin:{left:margin,right:margin},tableWidth:contentW,body:[['Marks / Notes',S.packs.map(x=>[x.marks,x.notes].filter(Boolean).join(' - ')).filter(Boolean).join(' | ')],['Official total source',S.useGeneralPack?'General shipment summary informed by Logistics':'Sum of individual item compositions']],theme:'grid',styles:{fontSize:6.8,cellPadding:1.8,lineColor:line},columnStyles:{0:{cellWidth:38,fontStyle:'bold'},1:{cellWidth:239}}});signature(d.lastAutoTable.finalY+4);footer();d.save((S.invoiceNo||'Central-Mesh-Export')+'.pdf');
}

ensureItemPacks();quietSave();if(currentStep===3)renderLogistics();
